services:
  php:
    build: .
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - app_network
    ports:
      - "3000:3000"

  mysql:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
